title: Aperitiiif 🥂
baseurl: /aperitiiif
url: ""
source: src
theme: just-the-docs
color_scheme: dark

aux_links_new_tab: true
aux_links:
  GitHub:
    - "https://github.com/middlicomp/aperitiiif"
callouts:
  note:
    title: Note
    color: purple
  optional:
    title: Optional
    color: green
